image: node:17.4.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - npm install
    - npm run build:prod
  script:
    - npm run test:unit

run_lint_tests:
  stage: test
  before_script:
    - npm install
    - npm run build:prod
  script:
    - npm run lint:ts
    - npm run lint:scss

run_integration_tests:
  tags:
    - local
    - docker
    - shell
  stage: test
  before_script:
    - nvm -v
    - npm -v
    - npm install
    - npm run build:prod
    - npm run storybook:build
  script:
    - npm run test:ui:ci

build_image:
  only:
    - main
  stage: build
  script:
    - echo "Building the docker image"
    - echo "Tagging the docker image"

push_image:
  only:
    - main
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging into docker registry"
    - echo "Pushing docker image to registry"

deploy_image:
  only:
    - main
  stage: deploy
  script:
    -echo "Deploying new docker image to dev server"